### ISSUE TITLE
What DB technology is best for CaronaBoard?

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#1]
**As...** the Creator of "CaronaBoard"
**I want to...** know what is the best DB technology given "CaronaBoard" concept and needs
**So that...** I know how can we start building the next version of the product

**Business Context:**
This story was created to get an opinion of experts on the technology to be chosen for DB. This is part of tech stack definition and it is a fundamental part to kick start this project well.

**Below follows some ideas to help drive discussion and decision around DB choice:**
1. Scale easily and be able to grow to support many users
2. Handle intense traffic of data, specially when we reach a point where we have features for real time communication (ex: chat)
3. Be interesting technology to offer technical challenges and attract developers that like innovation.
4. Flexible, to handle open source projects where the ideas and product roadmap can evolve to different directions. It should be also flexible to be migrated to other DB technology, as initially there is no money to fund this project.
5. Free of cost: initially the technology should be free of cost. In the future we can evolve to something more robust. This is one of the main criteria, and will invalidate previous criteria for the time being.

**Expected outcomes:**
1. Have a comparison of different technologies that can be used.
2. Have a final decision on how can start creating DB for CaronaBoard
3. Unfold other needs (ex: Storage, Domain, Deploy Pipeline, etc)

**Useful links**
1. [About Carona Board](https://github.com/luismizutani/CaronaBoard/wiki/About-CaronaBoard)
2. [Product concept](https://github.com/luismizutani/CaronaBoard/wiki/Product's-Concept)

**Comment by jeffhsta** [comment]
Hey @luismizutani I am not a DB specialist but, I think the best way to store this project data is using a NoSQL database.

I suggested MongoDB, it's document oriented, it's fast, easy to use, free of cost and I quite sure that is easy migrate from it to another solution in the future.

I don't know about the scalability, I have to search a bit for this, but anyway here is my cent =)

**Comment by othman853** [comment]
Hey! 

My personal opinion is that the MEAN stack would be nice for this project. I am currently using MEAN with Node 5.8 and ES6 and it seems nice, easy to maintain, very quick to set up and use and this ease of use and deploy would help to have CaronaBoard up ASAP. =)

**Comment by luismizutani** [comment]
Thanks @jeffhsta, I think your idea is similar to what @othman853 suggested. He also thinks MongoDB is a goos choice for the project. From what I heard configuration and cash is not so trivial.  I would like to hear a little from other around scalability of mongoDB.  If @glauberramos, @othman853 feel excited about MongoDB, I am ok with it, however I do not have any knowledge on how to set it up.

**Comment by glauberramos** [comment]
I like the idea of using mongoDB, it's easy to develop and fast as well. The only bad case of mongo is if the data is too relational. But I believe this is not the case for this project.

I was going to suggest to use Firebase for the first prototype as well. It is easier than using MongoDB and we can create a first version to start validating some assumptions.

**Comment by luismizutani** [comment]
@glauberramos I like the idea to start simple and fast. But in the future if we decide to move data from Firebase to other DB, would that be easy?

**Comment by glauberramos** [comment]
@luismizutani Firebase works very similar to a documented oriented database. It has a feature to export all the data so you can use it to import into another database.

**Comment by glauberramos** [comment]
What target are you thinking about? Start only with your local office or do you want to start with the whole country?

**Comment by luismizutani** [comment]
I guess we should start with Porto Alegre Office to validate whether people are using or not. Then after feedbacks and improving we can campaign and launch the app for BH, Recife e SP. The idea is to allow people to create groups, so after all TW offices we can open to other workplaces external to TW (but that will be future)

**Comment by glauberramos** [comment]
If we are going to start small, Firebase is a nice option.

**Comment by luismizutani** [comment]
@jeffhsta, @othman853, @glauberramos Let's start with Firebase?

**Comment by yrachid** [comment]
Well, I have no previous experience on Firebase, after taking a quick look it seemed really powerful to me. I'm in for Firebase and if that is the final decision, I will start taking a deeper look then hehehe.

**Comment by luismizutani** [comment]
Well done team! We already have our TECH STACK, which will be:
1. [Firebase (DB)](https://www.firebase.com/)
2. [Node.js](https://nodejs.org/en/)
3. [React](http://facebook.github.io/react/index.html)
4. [SASS](http://sass-lang.com/)
5. [Bootstrap](http://getbootstrap.com/)
