### ISSUE TITLE
What technology can we use to build the next version of CaronaBoard?

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#2]
As... the Creator of "CaronaBoard"
I want to... know what is the best technology given "CaronaBoard" concept and needs
So that... I know how can we start building the next version of the product

**Business Context**
This story was created to get an opinion of experts on the technology to be chosen to build the application.

**Expected outcomes**
1. Have a comparative view of advantages and disadvantages of each technology proposed
2. Have a final consensus of the team on what will we use.
3. Unfold other needs (ex: Storage, Domain, Deploy Pipeline, etc)

**Useful links**
1. [About Carona Board](https://github.com/luismizutani/CaronaBoard/wiki/About-CaronaBoard)
2. [Product concept](https://github.com/luismizutani/CaronaBoard/wiki/Product's-Concept)

**Comment by luismizutani** [comment]
I originally thought about using lightweight technologies such as Node.js or Rails. 

**I Would like to hear your thought on that!**

**Comment by yrachid** [comment]
Hey!

Personally, I would also be inclined to choose the MEAN stack. It is easy and fast to set up, deploy and maintain and it has a rich open source community with a lot of open source stuff. Also, it would be very easy to integrate with NoSql databases such as MongoDB.

As from my perspective, this stack would help to have CaronaBoard up very quickly. I am currently using Node.js 5.8 with ES6, Express and MongoDB with Mongoose and my experience has been very good with this stack until now. =)

**Comment by luismizutani** [comment]
Let's see who wants to participe in the project start and then made a decision. Your suggestion seem good, we can make a quick talk with some other folks interested in participating and see if all agree with this tech stack

**Comment by glauberramos** [comment]
I like MEAN stack as well. We can talk more about that. Because I had the initial idea to use firebase. But maybe MEAN is the best in this case.

**Comment by luismizutani** [comment]
For now we have 2 options:
1) MEAN stack
2) Firebase

@othman853 , @glauberramos , @jeffhsta I believe our preferred option is becoming MEAN stack. If you all agree we can go for it. Do you guys agree?

**Comment by luismizutani** [comment]
Well done team! We already have our TECH STACK, which will be:
1. [Firebase (DB)](https://www.firebase.com/)
2. [Node.js](https://nodejs.org/en/)
3. [React](http://facebook.github.io/react/index.html)
4. [SASS](http://sass-lang.com/)
