### ISSUE TITLE
Remove posted data from Git history

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#20]
The idea of this story is simple, to clean up any data that is now stored in DB.

For that we may find a tool that will clean this data, or we should simply remove old commits from a certain date backwards and start new product phase from scratch.

We can always have a backup somewhere safe if we would like to.

**Comment by rogeriochaves** [comment]
I've rewritten all git history to replace all names with Fulano(a), Siclano(a) and Beltrano(a), and replaced all seconds name with Silva.

Is that enough?

**Comment by luismizutani** [comment]
I believe it is! What about addresses? Do we believe it is a sensitive info?

If not I am ok with that.

**Comment by rogeriochaves** [comment]
Idk, I mean, those are common POA addresses, what do you think @jeffhsta?
