### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by jcmidia** [CaronaBoard/caronaboard#23]
Hi everyone,

I'm interest in this project, so I cloned the repo and tried to run locally to see how I could help.
But I think the README is outdate. I had to install Yarn and run the project with a different command.
I suggest to check it out to help possible new contributors.

**Comment by luismizutani** [comment]
Sorry Julio abd thanks for the warning. We will update and let you know ASAP

**Comment by rogeriochaves** [comment]
closed by #26
