### ISSUE TITLE
How should we manage CSS on CaronaBoard?

### ISSUE THREAD

**Issue by rogeriochaves** [CaronaBoard/caronaboard#44]
Hello!

@roberto, @jcmidia, @glauberramos, @lucaslago and @jeffhsta, I need your help with opinions here.

Right now, we are including materialize to be our base css, then we add our custom stylings on top of it with scss, this is the main.scss file. Also, we have a splash.scss file that is very very tiny and don’t need materialize, this is just for the splash screen to load as fast as possible.

For loading the scss we use webpack, but without css-loader and styles-loader, instead we use raw-loader and file-loader, so our css ends up separated from our js file.

The default for webpack is to use those loaders and to have css bundled together with the js file. The problem of not doing that is that we cannot use @import statements inside scss, that’s why we have a monolithic main.scss file right now, with all the rules.

If we did use css-loader and styles-loaders, we could still add extract-text-loader to keep css on a separate file. I haven’t did that yet because I wanted to keep webpack config as simple as possible (as webpack is already complicated for a lot of people)

Also, I feel like our css is not very well organized, and can become a mess very quickly.

Also (2), I wanted to try an alternative to integrate better with elm and attempt new things, with elm-css.

So, I have some important questions:

# 1 - Which language should we use?

So, scss is what we are using right now, and the most common way of doing css nowadays. But there is this new kid on the block for elm, elm-css, which allows doing css using elm and relying on its advantages, it borrows ideas from [css-modules](https://glenmaddern.com/articles/css-modules).
I’ll list some advantages and disadvantages I’ve though:

Advantages:

- We can learn something new, try, see if it has advantages, and maybe attract other hipsters into helping the project too
- Brings the advantages from [css-modules](https://glenmaddern.com/articles/css-modules)
- Type-Safe CSS!
- One less language in the codebase, it will be basically 100% elm
- Much better integration with the rest of our app
- It’s just code, we will be able to do ifs, loops, functions and everything in our css, crazy!

Disadvantages:

- Contributors will have an extra new thing to learn, and maybe will be harder for a css expert that is not an elm enthusiast 
- There is less tooling and less content available on the web for elm-css than for sass
- We have no experience in it, so there are risks of unexpected problems that we never been through
- Materialize is pure css, so even if we use elm-css our views will still have to use tradicional class names that include the stylings from materialize (unless elm-css has a clever way of doing that)

# 2 - How should we organize our css?

The main.scss file and class names are getting disorganized already, how do we deal with it? Split in different files, one for each module (Login, Rides, etc)? Should the stylesheet live inside the module? Do we always use classes or use IDs for unique elements?

If we keep sass, what conventions we use? Should we follow something like BEM? I’m afraid the materialize classes doesn’t follow a single well stablished convention, how do we fit them in?

If we use elm-css, I believe we should take the css-modules approach (very well described [here](https://glenmaddern.com/articles/css-modules)). I like that approach, naming is a hard thing, and with that we can avoid a bit of naming, no need for thinking in clever ways of simulating namespace. But again, how do we mix materialize classes in?

# 3 - Should we have our css separate from our javascript bundle?

So, the advantages of having a separate stylesheet that I can think of are:

a) Load CSS before JS finishes so our HTML gets styled before our app finishes loading
b) Cache CSS separately so the user can reuse it when navigating through different pages

**But**:

a) We already have a separate CSS for loading the splash screen blazing fast, and the full app css is only applied after the app finishes loading anyway
b) CaronaBoard is a SPA, it is always the same HTML/CSS/JS, there is no advantage in caching separately 

What do you think? If we don’t extract our CSS to a separate file, the webpack config would be probably simpler for both scss and elm-css. I couldn’t think of any other advantages to worth the effort.

Happy Carnaval everyone ;)

**Comment by jcmidia** [comment]
Hello! How were your holidays guys?

For me, the best way is write the CSS from zero using only the material elements and styles we need.
So, by this way, we could use elm-css and the css-modules concept. It would be perfect! I think this idea talks very well with elm. And we should not have the problems 2 and 3.

But maybe, rewrite the entire css is not the priority for now. So, we could keep the material css as  external stylesheet, like a kind of reset.css, and start using the css-modules to customize the elements.
The ideia is start just customizing the elements, but after a time, we should have the entire styles of the element in the elm-css. So, after it, we can remove the material css :)

What do you think about it?

**Comment by glauberramos** [comment]
Hey @rogeriochaves I will share some ideas here. I don't have much experience with elm-css (but who has? hehehe), anyway, I think CSS in JS is probably the future, and we will see much more things like that on more projects. But for now I have more experience with SCSS.

I usually don't use any framework (like bootstrap, materialize or foundation), I prefer keeping things simple and use a normalize file, and use react component architecture to keep the CSS organized. But I understand that is nice to use a framework on the beginning to save time and add some nice styles. 

Some tips:

- Use [normalize.css](https://necolas.github.io/normalize.css/), this helps keeping your site looking the same on every browser
- Have a file for variables (colors, fonts, sizes, media queries) (you will need to use style-loader to use import)
- Use [PostCSS](http://postcss.org/), this guy is amazing, you can use Autoprefixer to avoid writing vendors prefixers (-ms, -webkit, etc)
- Keep the .scss file inside the component folder, so when you are changing a component you change everything in the same folder.
- Avoid using ID's inside the .scss file, also avoid using !important. Those 2 things messes up with the selectors hierarchy and it can cause big problems when the project gets bigger.
- Don't target elements on the CSS as well (like a or div), it's always better to use classes. Let take this example: `.car a`. The browser reads the CSS selector from right to left, so it will look for all the links on the page to start, this is not optimized, it is better to use a class.
- Use a consistent class naming pattern, imagine a component called "Car". The file should be `car.scss`, the class should be the same name of the component `.car`, every element inside should keep car `.car-child`, and modifiers as well `.car-child-active`. BEM works fine for that (but it has ugly syntax). This will help to avoid one component influencing on other component, so don't worry if you think you are repeating CSS here, the idea is to have the component self-contained.
- Use [Stylelint](https://github.com/stylelint/stylelint), this will help with typeSafe CSS and other things, like setting a max nesting of 3 levels (this is important as well)
- Use [CSSComb](http://csscomb.com/), this is less important but it will organize the properties when you save the file, you can add that on sublime or atom
- Also take a look on this [post](https://github.com/jareware/css-architecture), it summarizes very well the basics for a good CSS architecture

I hope this helps.

**Comment by luismizutani** [comment]
Thanks Glauber!!!

**Comment by rogeriochaves** [comment]
Thanks for the comments everybody, very helpful! I've started playing with elm-css but it was so fun that I've ended up doing the whole migration already, check it out and please comment if it makes sense with what you told: #45

**Comment by luismizutani** [comment]
Galera,

Agora mesmo estou num cabify, debaixo de muita chuva e que demorou muito. Alem disso caro pelo pico de demanda.

Eu que sou um dos maiores defensores do caronaboard, nao me toquei (na loucura do dia-a-dia) de verificar se alguem ia pra kinha casa. Acontece que haviam 2 pessoas que poderiam ter me dado carona.

Ai fiquei pensando naquela ideia de integrar com alguma app de previsão do tempo e disparar um email incentivando o uso do carona board toda vez que a probabilidade de chuva estiver acima de um certo nivel (ex: acima de 70%)

Isto pode alavancar o uso e consequentemente feedback para evolução do produto.

O que acham da ideia?

Abs

**Comment by rogeriochaves** [comment]
@luismizutani claro! Tem como usar até o IFTTT pra isso, ao menos pra uma versão inicial, só num achei uma forma de limitar pros dias da semana:

![image](https://user-images.githubusercontent.com/792201/26951329-1b6ecafe-4c77-11e7-9fff-eeff76e13ecd.png)

de qualquer forma acho que aqui não é o local correto pra essa discussão hahaha, podemos iniciar uma nova issue

**Comment by rogeriochaves** [comment]
o chato também é que estando em Porto Alegre ele vai enviar esse email basicamente todos os dias hahaha

**Comment by luismizutani** [comment]
Hahaha, vou criar uma issue para a gente trocar ideia
