### ISSUE TITLE
Validate users who can access list of "Caronas"

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#5]
As a... a user offering ride
I want... CaronaBoard to validate users who can access information
So that... I know only people I trust is viewing information I posted

**BUSINESS CONTEXT**

We would like to add a layer of security to the product. However we believe that the ideal state is that users can join a group of rides upon approval of group member. This is not a trivial work, so for the start we will work with ThoughtWorks employees as our beta users, and to deliver value fast we will implement a simple validation using email from thoughtworks.

In the future this initial group of users will become the first group of many inside the product and we will implement a login system that is not based on email validation.

**ACCEPTANCE CRITERIA**
#1.

Given I am a user
When I access caronaboard.com
Than I should see a login screen that will ask for my email

#2.
Given I am a Thoughtworkwer (using TW's email)
When I submit my email in the initial login page
Than I should be loaded with the page of carona
And I should have access to all current functions (* see notes)

#3.
Given I am a NOT Thoughtworkwer
When I submit my email in the initial login page
Than I should be see a message that the product still open for a beta test group (or something like that)
And ideally I should save their email for future marketing campaign

NOTES
- With login, will all previous features keep working?
- Will we start implementing any test?
- If we are to have tests should we thing about migrating the service to another server?

Please see: https://github.com/CaronaBoard/caronaboard/wiki/3.-MVP3's---Information-workflow for more details on current features and workflow.

**Comment by luismizutani** [comment]
@glauberramos and I talked about using facebook login, that is available in Firebase. According to Glauber is easy to implement (apparently). What do you ( @andressa , @jeffhsta , @jonathanrz , @othman853 ) think?

**Comment by yrachid** [comment]
Seems like a good idea! I only have two questions about this approach: 

1 - Since we're using Firebase only as our database and not as the whole backend (as far as I know hehe), would this feature still be available for us to secure our own Node.js API? 

2 - Are we, at the present moment, considering to open the CaronaBoard for people from outside TW? As I understand, having a FB Authentication would allow people from outside ThoughtWorks to register now. Are we planning to support this by now or only in the future?

**Comment by luismizutani** [comment]
Very good points indeed. I was not seeing from this angle.

I guess we are not ready to support user from outside TW.

One alternative option would be to use Okta login as our solution by now. I has the advantage that we won't need to capture user email everytime someone ask for a ride.

 In the future if we succed scaling up the application to other TW offices we can thing about open it to externak public.

Does everyone agreea that by now, the simpler pathway is to go with okta login?

**Comment by andressa** [comment]
I like the idea of using okta, although I have no (technical) ideia on how to implement it.

But, I believe I have a better idea:
What if we only protect everything validating with TW username using jigsaw API?

https://jigsaw.thoughtworks.com/api-docs/get-people-id

**Comment by luismizutani** [comment]
Hi Andressa, sorry for the late reply. These day were busy.

I have no clue about how Jigsaw Api works, so it would be nice if you can
explain your idea a little more. can you do that?

What would be the benefit of using Jigsaw Api rather than okta? (ex: it is
easier to implement? it would cover more TW offices?, etc)

Reminder: The idea is to expand user base to other offices in Brazil.

Regards

2016-04-13 0:00 GMT-03:00 Andressa Sivolella notifications@github.com:

> I like the idea of using okta, although I have no (technical) ideia on how
> to implement it.
> 
> But, I believe I have a better idea:
> What if we only protect everything validating with TW username using
> jigsaw API?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/CaronaBoard/caronaboard/issues/5#issuecomment-209204741

## 

_Atenciosamente,_

_Luis Fernando Mizutani_

**Comment by andressa** [comment]
Trying to implement it following the documentation below:
https://github.com/ThoughtWorksInc/okta-samples

**Comment by luismizutani** [comment]
oi Andressa, vi que voce está tentando fazer funcionar o okta. Alguma
evolução. podemos fazer um seção esta semana, o que acha?

2016-05-02 13:44 GMT-03:00 Andressa Sivolella notifications@github.com:

> Trying to implement it following the documentation below:
> https://github.com/ThoughtWorksInc/okta-samples
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/CaronaBoard/caronaboard/issues/5#issuecomment-216288616

## 

_Atenciosamente,_

_Luis Fernando Mizutani_

**Comment by andressa** [comment]
Probably, we need some configuration from okta, and I still did not understand what need to be done.

Here is the node+express+okta integration link:
https://github.com/ThoughtWorksInc/okta-samples/tree/master/okta-node-express

**Comment by luismizutani** [comment]
Yes, Rafa told me once that TechOps guys need to give us some access to a Okta config console.

I am not quite sure about how to do it. I think Laimer know how to do it. I will ask him

**Comment by luismizutani** [comment]
Pessoal, na nossa pasta compartilhada do CaronaBoard (google drive). Existe uma subpasta que tem os HTMLs que serão exibidos quando um usuário logado tentar buscar mais informações sobre a rota.

**Comment by lucaslago** [comment]
@luismizutani Could I have access to that drive folder?

**Comment by lucaslago** [comment]
I'd like to pair with someone on this issue, anyone up for it?

**Comment by luismizutani** [comment]
Hi @lucaslago Lucas, I think I cannot help you on that. Sorry for late reply I was on vacations and not reading my emails. There are some new people on the team and they are willing to work on the project too.

Ah! I would like to use this opportunity to thank you all @lucaslago @jeffhsta @andressa @glauberramos @othman853 for the time you guys spent doing this work. I could see the project has evolved a lot since I was absent.

**Comment by rogeriochaves** [comment]
Okay I disagree with having Okta integration (at least for now).

It will make it easier for all thoughtworkers like us, but prevent everyone else from using it and to validade this project outside our bubble

I don't believe TWrks will mind saving one more login/password or login with facebook/whatever.

At first we could simply have login, then we can implement the ideas of communities like Mizu said, the community could have one or more admins, and one of those community would be TW :)

And _then_ we could provide SAML integration for those who want it (far future IMO)

**Comment by lucaslago** [comment]
I agree with @rogeriochaves. Plus, Okta integration adds an extra layer of bureaucracy (tw labs testing and checks before going to prod, Okta sandbox, etc) that would slow us down in delivering this feature.

**Comment by luismizutani** [comment]
E o que ficou decidido no final? Vamos usar outro login (alternativo ao Okta)?

**Comment by luismizutani** [comment]
Ok guys, feel free to choose any login system that you like. My only recommendation is to choose one that is simple to implement as well as safe enough. Lets keep it simple and evolve with the need!

Enviada do meu iPhone

**Comment by luismizutani** [comment]
People, I updated this issue based on last conversation with @rogeriochaves and Roberto.

I added some minor details such as saving peoples email (when ar not TWrs) for future marketig campaigns. I advise you to take a look at the content. It is pretty simple but changed since the card was created
