### ISSUE TITLE
Vocabulário / Vocabulary

### ISSUE THREAD

**Issue by rogeriochaves** [CaronaBoard/caronaboard#52]
Hello, I'm starting to read about DDD, and one thing that is very restated there is that we need to define a vocabulary, a **ubiquitous language** for the domain.

Turns out it is very hard to name things in caronaboard, too much ambiguity. I've thought about it a lot together with Laura Paschoal (my fiancé) about it and we came to this:

English Vocabulary
----

**Drivers** - people who have a car and are willing to give _rides_ to _passengers_

**Passengers** - people who want _rides_ from _drivers_

**Ride** - when a _driver_ carries a _passenger_

**Ride Offer** - when a _driver_ proactively registers his/hers _ride offer_ so other _passengers_ can see
> scenario: "I have a car and I can give rides"

**Ride Request** - when a _passenger_ chooses a _ride offer_, issuing a notification to the _driver_
> scenario: "I don't have a car, Suze is offering a ride to X, I'll ask her for a ride"

**Wanted Ride** - when a _passenger_ proactively registers his/hers _wanted rides_ so the _drivers_ can see them
> scenario: "I don't have a car and I need rides"

**Ride Suggestion** - when a _driver_ suggests a _wanted ride_ to a _passenger_
> scenario: "I have a car, I saw that Joe needs a ride to X, I'll offer him one"

### UI

| What the user reads | What the user sees |
|---|---|
| I have a car | Wished rides list |
| I want a ride | Offered rides list |
| I have a car + Add | Form for adding a new ride offer |
| I want a ride + Add | Form for adding a new wanted ride |
| Give ride | Suggest a ride for a passenger |
| Ask for a ride | Request a ride for the driver |

Vocabulário em Português
----

**Motoristas** - pessoas que tem um carro e estão dispostas a dar _carona_ para _passageiros_

**Passageiros** - pessoas que querem _carona_ de _motoristas_

**Carona** - quando um _motorista_ carrega um _passageiro_

**Carona Ofertada** - quando um _motorista_ proativamente cadastra sua _oferta de carona_ para que _passageiros_ possam vê-la 
> cenário: "Tenho um carro e posso dar caronas"

**Pedido de Carona** - quando um _passageiro_ escolhe uma _carona ofertada_ por um motorista
> cenário: "não tenho carro, vi que fulana está oferecendo carona pra X, vou pedir uma carona para ela"

**Carona Desejada** - quando um _passageiro_ proativamente cadastra sua _carona desejada_ para que _motoristas_ possam vê-la
> cenário: "Não tenho carro e preciso de caronas"

**Sugestão de Carona** - quando um _motorista_ encontra uma _carona desejada_ por um passageiro e sugere sua carona
> cenário: "Tenho um carro e vi que fulano precisa ir pra X também, vou oferecer uma carona pra ele"

### UI

| O que o usuário lê | O que o usuarios vê |
|---|---|
| Tenho carro | Lista de caronas desejadas |
| Quero carona | Lista de caronas ofertadas |
| Tenho carro + adicionar | Cadastro de oferta de carona |
| Quero carona + adicionar | Cadastro de desejo de carona |
| Dar carona | Sugestão de carona para passageiro |
| Pedir carona | Pedido de carona para motorista |

**Comment by rogeriochaves** [comment]
what you think @luismizutani, @jcmidia, @thiagorocha23, @taniadgv, @eduardomoroni?

**Comment by eduardomoroni** [comment]
Wow, Sounds perfect to me!

**Comment by thiagorocha23** [comment]
I liked, sounds clear and simple. =]

**Comment by luismizutani** [comment]
I think this is awesome!!! Makes perfect sense to me!

**Comment by luismizutani** [comment]
Should we add this glossary to our wiki as a guideline for development? If you agree we can move this content to this new section, and close that story.

**Comment by eduardomoroni** [comment]
Makes more sense having this as wiki, since the issues intention was
validate with coworkers whether this vocabulary is suitable or not.
We all agreed that this vocabulary is awesome.

PS.: Should we speak in Portuguese? Could this make the project easier to
contribute to?

Em ter, 24 de out de 2017 às 13:34, Luis Mizutani <notifications@github.com>
escreveu:

**Comment by luismizutani** [comment]
Feito! Done!!!
Incluí o conteúdo na Wiki, na seção [Guias para desenvolvimento de produto.](https://github.com/CaronaBoard/caronaboard/wiki/4.-Guias-para-o-desenvolvimento-de-produto-%7C-Product-development-guidelines)

I included the content under the session Product Development Guidelines.
