### ISSUE TITLE
Configure React for Environment

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#6]
h2. Scope

Accomplish configuration of React and Firebase, so team can start developing features.

**Comment by luismizutani** [comment]
oi @glauberramos voce começou a fazer algo neste card? Vi que há um commit seu. Abs

**Comment by glauberramos** [comment]
Oi Mizu,

Sim eu terminei de configurar o react.

**Comment by luismizutani** [comment]
Is this done? Should we move the issue to DONE?

**Comment by andressa** [comment]
I'm closing this story, as we have already an accepted PR
https://github.com/CaronaBoard/caronaboard/pull/7
