### ISSUE TITLE
Manter consistencia durante atualizaçāo de perfil

### ISSUE THREAD

**Issue by eduardomoroni** [CaronaBoard/caronaboard#67]
Entendo as limitaçōes que o firebase nos traz.
Cheguei num cenário complicado de contornar sem mudar a representaçāo dos dados.

Atualizar perfil:
Quando um usuário atualiza seu perfil, precisamos atualizar TODOS os pedidos de carona deste usuário e TODAS as ofertas de carona deste usuário.
Problema:
O documento que armazena informaçōes de pedidos de carona segue a seguinte estrutura, usando a notaçāo do [flow-typed](https://flow.org/en/docs/types/objects/)
```
[rideId: string]: {
   [requestId: string]: {
      profile: {
        name: string,
        contact: {
          kind: string,
          value: string
        }
     }
   }
}
```
Para eu conseguir atualizar preciso buscar todos os `Rides` o que me faria retornar TODOS os objetos de carona.
Minha sugestāo é inserir o userId dentro do profile.

Alguem teria outra sugestāo?

Anexando imagem para facilitar entendimento:
![image](https://user-images.githubusercontent.com/823150/30979889-7c06aa54-a455-11e7-897e-64f456116daf.png)

**Comment by eduardomoroni** [comment]
Aconteceu algo semelhante quando tentei buscar Todas os pedidos de carona de um usuário 😅

**Comment by luismizutani** [comment]
Isto me traz uma dúvida. Para o nosso produto existe alguma vantagem real em usar uma base não relacional?

**Comment by eduardomoroni** [comment]
Eu havia conversado com @rogeriochaves sobre isso, a ideia de usar o firebase para o MVP foi devido a simplicidade de lidar com autenticaçāo, push notification e ter um banco que poderiamos usar facilmente. A medida que o projeto foi sendo desenvolvido começou a ficar evidente que o modulo de banco de dados do firebase nāo é tāo eficaz para o nosso uso.

**Comment by eduardomoroni** [comment]
fechando a issue pois o PR já foi mergeado, mas podemos continuar a conversa aqui caso necessario. 🤠

**Comment by rogeriochaves** [comment]
@eduardomoroni sim, acho que o firebase nos atrapalha bastante na real, seria muito bom trocar pra um relacional.

Mas acho que dá pra reaproveitar o firebase só pras notificações e talvez até pra autenticação, e deixar o relacional pros dados mesmo
