### ISSUE TITLE
Approval of user request to participar em BH and POA Groups

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#68]
**Context**
I sent and email to recruit user to use the product. I received good feedback and many people enrolled in the App. Now they are sending requests to join the existent groups (POA and BH).

**What is required in this card**
Someone needs to approve users so they can offer ride and use the product. Right now, the only person with Admin rights to approve users in the group is @rogeriochaves . He is on vacations now, so I am qui9te unsure if he will see that issue.

**Learnings**
We need to give approval rights to a wider group of people (including myself), and we should ask Rogerio to give us more insights on how to do it.

**Comment by rogeriochaves** [comment]
Sorry, just saw that now. Yeah, right now the only way to set someone as admin is changing directly on the database, but I believe at least you and @eduardomoroni have access to the prod database too right?

First you have to find which id is yours, under profiles, this is yours mizu:

<img width="415" alt="image" src="https://user-images.githubusercontent.com/792201/31504259-4d26ac0e-af48-11e7-8688-c169fe6a78d0.png">

Then on the groups, change your id under members to admin: true, like this:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/792201/31504294-61db2de6-af48-11e7-9e1c-805fa558de7d.png">

You are admin of both twpoa and twbh now @luismizutani, also, I've accepted everyone's request (there was a bunch of people waiting to be accepted, twpoa now has 19 members)

**Comment by luismizutani** [comment]
Nice Rogerio, we already have a few ride offers and several users. People in Belo Horizonte is excited and will probably start using too.
