### ISSUE TITLE
Receber aviso quando sou aceito em um grupo / Be warned when I am accepted to join a group

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#72]
**COMO** um dono de um grupo de carona
**QUERO** que novos membros sejam avisados quando forem aprovados em uma grupo
**ASSIM** eles podem começar a solicitar e/ou oferecer carona no grupo

### CONTEXTO:
Para solicitar ou oferecer carona para um grupo voce deverá solicitar aprovação para a pessoa dona do grupo. Quando esta pessoa aprova sua participação, você já pode ver as caronas sendo oferecidas por outros como também poderá você mesmo oferecer uma carona. Esta história irá implementar um aviso para que voce saiba quando foi aprovado

### CRITÉRIO DE ACEITAÇÃO:
DADO que sou um usuário que pediu permissão para participar de um grupo
QUANDO a pessoa dona do grupo me dá permissão para participar do grupo
ENTÃO eu devo poder acessar aquele grupo
E devo receber um email informando que agora eu sou um membro daquele grupo

A mensagem de email será simples, algo como;

> _Oi, bem vindo ao grupo <nome do grupo> no CaronaBoard._
> 
> Agora você pode oferecer carona para outras pessoas no grupo_
> _OR_
> _voce pode solicitar carona selecionando uma das rotas oferecidas._
> 
> _Tenha uma ótima carona!_
> 
> _Abraço,_
> Equipe CaronaBoard_

_English_

AS A owner of a group
I WANT new group members to be warned when they are approved in a group
SO THAT they can offer or request a ride in the group

### ACCEPTANCE CRITERIA
Given I am user that requested access to a group
When the owner of that group give me permission to join the group
Then I should be able to access the group section
And I should be sent an email telling me I am now part of the group

Message for the email can start simple, something along these lines:

> _Hi, welcome to the group <name of group> on CaronaBoard._
> 
> _Now you can offer ride (with link for give ride) to people in the group_
> _OR_
> _You can ask for ride by selecting the route you wish._
> 
> _Have a nice ride!_
> 
> _All the best,_
> _Team CaronaBoard_

**Comment by rogeriochaves** [comment]
Currently we only ask for permission to send notifications when creating a ride, it's important to remember that we'll need to ask permission for notification when the person ask to join a group now, else it won't work

**Comment by rogeriochaves** [comment]
Ao invés de email eu coloquei uma simples notificação, por ser mais facil de configurar:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/792201/33888692-fa920c96-df34-11e7-9d96-97c10e170b4a.png">

implementado em [b8dc627335](https://github.com/CaronaBoard/caronaboard-firebase-functions/commit/b8dc627335fdd8e00f44a73c485d60757345e6f3)

**Comment by rogeriochaves** [comment]
vou fechar a issue, se tiver algo mais reabre ;)

**Comment by luismizutani** [comment]
Ficou muito boa a notificação! Esta funcionalidade é apenas no desktop ou tb no mobile site?

**Comment by rogeriochaves** [comment]
no mobile só para android, iOS ainda nao tem suporte a isso
