### ISSUE TITLE
Página não carrega na primeira vez que acesso logado / when already logged in page does not load properly

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#74]
Considerando que já estou logado (opção de me manter logado mesmo ao sair do site). Quando abro meu browser e acesso o carona board, a tela carrega o topo o do site mas o conteúdo central (lista de grupos) não carrega. Ao atualizar a página o conteúdo é carregado normalmente.

_Considering I am already logged in (option to keep logged after leave the site). When I opened the browser and access CaronaBoard, the header is loaded but the main content (list of groups) does not load. When I refresh the page the content is loaded normally._

**Comment by rogeriochaves** [comment]
eu *acho* que corrigi o problema no commit [4a3285](https://github.com/CaronaBoard/caronaboard/commit/4a3285fd9d1c31f2a78bb38732a7b339c04ad177), mas como era meio dificil de reproduzir o problema, pode conferir pra mim?

por causa de cache primeiro vc tem que abrir, esperar o app atualizar (alguns segundinhos) e na proxima aba já deve funcionar. Ou testar numa janela privada

**Comment by rogeriochaves** [comment]
parece estar funcionando sim, se ainda tiver com problemas avisa 👍

**Comment by luismizutani** [comment]
Vou testar sim!
