### ISSUE TITLE
Esqueci minha senha / I forgot my password

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#75]
As a user
I want to receive a link to reset my password
So that I can register a new when I forgot my original password

**Comment by rogeriochaves** [comment]
essa funcionalidade já existe:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/792201/33888968-cea2c138-df35-11e7-8b4a-9049a8138513.png">

o usuário recebe um email do firebase
