### ISSUE TITLE
Configure DB for CaronaBoard

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#8]
First question: Do we all think Firebase is the best choice at least for the start?

Basically we need to replace the current logic where all data is stored in Google Spreadsheets, to a better solution. For that, we need to develop a few features, grounded in a DB solution.

We can improve that card.

**Comment by luismizutani** [comment]
Do we have any update on that? Anyone has any idea on which DB should we use?

**Comment by luanReis** [comment]
We (André and I) did some research about the Firebase and we were able to implement a simple solution to fetch the data from a Firebase instance and render on the main screen. We're not that experienced with React ecosystem but based on our research this seems to be the simplest solution.

**Comment by rogeriochaves** [comment]
+1 for firebase

Firebase has been used successfully in funretro (https://funretro.github.io/distributed/) and has an user authentication feature in-place, so it could help us with the security matter as well

**Comment by luismizutani** [comment]
Estas estórias ainda são válidas? Estamos desenvolvendo isso?
