### ISSUE TITLE
Create CI pipeline

### ISSUE THREAD

**Issue by luismizutani** [CaronaBoard/caronaboard#9]
We do think would be great to have a configured CI pipeline. 

Question: which tool are we going to use? Options:
1. Snap CI
2. Travis
3. Other ideas?

**Comment by lucaslago** [comment]
How complex would that pipeline need to be? Would the following flow be enough?
push code to github master branch -> Run tests on CI -> if everything passes, deploy new version on heroku

**Comment by andressa** [comment]
👍 I agree with this approach!

**Comment by lucaslago** [comment]
I can't say anything for Snap CI, since I have no experience with it. But using Travis we can have that pipeline/workflow in a few minutes of configuration.

**Comment by luismizutani** [comment]
Do we have any preference. According to some folks here, Travis may have a
bigger community so troubleshooting might be easier. Snap on the other hand
is from TW and seems also a to be a good lightweight tool.

What do you think?

2016-06-03 14:20 GMT-03:00 Lucas Lago notifications@github.com:

> I can't say anything for Snap CI, since I have no experience with it. But
> using Travis we can have that pipeline/workflow in a few minutes of
> configuration.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/CaronaBoard/caronaboard/issues/9#issuecomment-223639527,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADTzFuymt1X10X-V7pcfwJdwBOhg8uelks5qIGJwgaJpZM4ItDXG
> .

## 

_Atenciosamente,_

_Luis Fernando Mizutani_

**Comment by lucaslago** [comment]
My preference goes to Travis for the reasons stated + easy setup, what's @CaronaBoard opinion on this?
